;;; Automatically generated by ‘recentf’ on Sat Dec 20 00:23:32 2025.

(setq recentf-list
      '(
        "~/.emacs.d/lisp/init-basic.el"
        "~/.emacs.d/init.el"
        "~/.emacs.d/lisp/init-lsp-package.el"
        "~/Sec/Code/CPP/test1.c"
        "~/.emacs.d/.gitignore"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
