;;; Automatically generated by ‘recentf’ on Tue Dec 23 17:02:44 2025.

(setq recentf-list
      '(
        "~/.config/fish/config.fish"
        "~/.emacs.d/lisp/init-lsp-package.el"
        "~/.emacs.d/lisp/init-basic.el"
        "~/Sec/Code/Java/study/study1.java"
        "~/.emacs.d/init.el"
        "~/.emacs.d/elpa/flymd-20160617.1214/flymd.el"
        "~/Work/AH/大数据局/账号记录.md"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
